$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: endpoint-managed-fashion-2
model: azureml:model-tf-fashion:1
code_configuration:
  code:
    local_path: ../../tf-src/
  scoring_script: score.py
environment: azureml:AzureML-tensorflow-2.4-ubuntu18.04-py37-cpu-inference:11
instance_type: Standard_DS3_v2
instance_count: 1
